In [7]:
import csv
import pandas as pd

df = pd.read_csv('/home/cgraaaj/Projects/cgr-trades/GFDLNFO_TICK_03062021/Options/RELIANCE24JUN212200CE.NFO.csv')
df.head(10)

,Ticker,Date,Time,LTP,BuyPrice,BuyQty,SellPrice,SellQty,LTQ,OpenInterest
0,RELIANCE24JUN212200CE.NFO,03/06/2021,09:15:00,81.00,73.10,3000,80.65,250,2500,4668500
1,RELIANCE24JUN212200CE.NFO,03/06/2021,09:15:00,81.00,73.10,3000,80.65,250,0,4668500
2,RELIANCE24JUN212200CE.NFO,03/06/2021,09:15:00,85.00,73.10,3000,80.65,250,0,4668500
3,RELIANCE24JUN212200CE.NFO,03/06/2021,09:15:00,73.20,73.10,3000,80.65,250,0,4668500
4,RELIANCE24JUN212200CE.NFO,03/06/2021,09:15:01,77.00,74.65,250,77.00,250,1000,4668500
5,RELIANCE24JUN212200CE.NFO,03/06/2021,09:15:02,79.20,78.10,250,80.60,250,1750,4668500
6,RELIANCE24JUN212200CE.NFO,03/06/2021,09:15:03,80.00,80.00,1250,80.70,250,500,4668500
7,RELIANCE24JUN212200CE.NFO,03/06/2021,09:15:04,80.45,80.40,250,81.80,250,4750,4668500
8,RELIANCE24JUN212200CE.NFO,03/06/2021,09:15:05,81.10,80.10,250,81.15,250,1500,4668500
9,RELIANCE24JUN212200CE.NFO,03/06/2021,09:15:06,80.30,80.35,250,81.30,250,3000,4668500

In [8]:
# Convert the time column to datetime
# df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S')
df["Date_Time"] = df['Date'].astype(str) + df['Time'].astype(str)

df['Date_Time'] = pd.to_datetime(df['Date_Time'], format='%d/%m/%Y%H:%M:%S')
df.insert(1, "Date_Time", df.pop('Date_Time'))
df = df.drop(df.columns[[2,3]], axis=1)

In [9]:
# def round_to_nearest_interval(time, interval):
#     minute = time.minute
#     # Round to the nearest interval
#     rounded_minute = interval * round(minute / interval)
#     if rounded_minute == 60:
#         time = time + pd.Timedelta(hours=1)
#         rounded_minute = 0
#     return time.replace(minute=rounded_minute, second=0)
# df['rounded_to_1min'] = df['Time'].apply(lambda x: round_to_nearest_interval(x, 1)).dt.strftime('%H:%M:%S')
# df['rounded_to_5min'] = df['Time'].apply(lambda x: round_to_nearest_interval(x, 5)).dt.strftime('%H:%M:%S')
# df['rounded_to_15min'] = df['Time'].apply(lambda x: round_to_nearest_interval(x, 15)).dt.strftime('%H:%M:%S')

In [10]:
# df.head(20)

In [11]:
# df.groupby('rounded_to_1min')[['LTP']].mean().round().reset_index()

In [12]:
df['Date_Time'] = pd.to_datetime(df['Date_Time'])
# Set the Date_Time column as the index
df.set_index('Date_Time', inplace=True)
ohlc_dict = {'LTP': ['first', 'max', 'min', 'last'],'OpenInterest': 'last'}
ohlc_df = df.resample('1T').agg(ohlc_dict)
ohlc_df.columns = ['Open', 'High', 'Low', 'Close', 'OpenInterest']

# Calculate the change in price (LTP) and OpenInterest
ohlc_df['OpenInterest_Change'] = ohlc_df['OpenInterest'].diff()
ohlc_df['LTP'] = ohlc_df['Close']
ohlc_df['Price_Change'] = ohlc_df['Close'].diff()

print(ohlc_df)

                     Open   High    Low  Close  OpenInterest  \
Date_Time
2021-06-03 09:15:00  81.0  87.00  73.20  85.15       4668500
2021-06-03 09:16:00  85.0  85.90  81.20  81.90       4668500
2021-06-03 09:17:00  81.4  82.15  80.65  81.80       4604250
2021-06-03 09:18:00  81.8  84.70  81.50  84.65       4604250
2021-06-03 09:19:00  84.5  86.70  84.50  85.90       4604250
...                   ...    ...    ...    ...           ...
2021-06-03 15:25:00  73.3  73.50  72.50  73.00       4282500
2021-06-03 15:26:00  73.0  73.00  71.10  71.10       4282500
2021-06-03 15:27:00  71.2  71.20  70.10  70.85       4282500
2021-06-03 15:28:00  70.8  71.00  70.70  71.00       4296250
2021-06-03 15:29:00  71.0  71.70  70.70  71.60       4296250

                     OpenInterest_Change    LTP  Price_Change
Date_Time
2021-06-03 09:15:00                  NaN  85.15           NaN
2021-06-03 09:16:00                  0.0  81.90         -3.25
2021-06-03 09:17:00             -64250.0  81.80         -0.10
2021-06-03 09:18:00                  0.0  84.65          2.85
2021-06-03 09:19:00                  0.0  85.90          1.25
...                                  ...    ...           ...
2021-06-03 15:25:00              -9250.0  73.00         -0.30
2021-06-03 15:26:00                  0.0  71.10         -1.90
2021-06-03 15:27:00                  0.0  70.85         -0.25
2021-06-03 15:28:00              13750.0  71.00          0.15
2021-06-03 15:29:00                  0.0  71.60          0.60

[375 rows x 8 columns]